version: '3.7'

services:
  #apiGateway service
  api-gateway:
    build:
      context: ./api-gateway
    restart: always
    ports:
      - '8888:8888'

#user microservice
  users:
    restart: on-failure
    build:
      context: ./user-service
    ports:
      - '7000:7000'

  #user microservice
  external-data:
    restart: on-failure
    build:
      context: ./exteranaldatasservice
    ports:
      - '4567:4567'

  #user microservice
  mobile-payment:
    restart: on-failure
    build:
      context: ./mobile-payment-service
    ports:
      - '5000:5000'

  #bitcoin-money microservice
  bitcoin-money:
    restart: on-failure
    build:
      context: ./bitcoin-money-service
    ports:
      - '3333:3333'
