version: '3'
services:

  #PHP Service
  laravel_lumen_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: laravel_lumen_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini


  #Nginx Service
  nginx-lumen-wrapped:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/


#Volumes
volumes:
  dbdata:
    driver: local

networks:
  default:
    external:
      name: StackMoney_Network_Overlay
